#!/bin/bash
if [ -z "$1" ]
  then
    git commit -m 'localize: ' -e
  else
    if [ -z "$2" ]
      then
        git commit -m "localize: $1"
      else
        echo "localize($1): $2"
        git commit -m "localize($1): $2"
    fi
fi
