#!/bin/bash
if [ -z "$1" ]
  then
    git commit -m 'docs: ' -e
  else
    if [ -z "$2" ]
      then
        git commit -m "docs: $1"
      else
        echo "docs($1): $2"
        git commit -m "docs($1): $2"
    fi
fi
